language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
notifications:
  email:
    recipients:
      - William.Isley@cgu.edu
      - meera.chowhan@gmail.com
      - Abbas.Albekhit@cgu.edu
    on_success: always # default: change
    on_failure: always # default: always

